# Your updated GitHub Actions workflow file
name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install specific compatible version of ipython
        pip install ipython==8.18.1 
        pip install -r requirements.txt

    - name: Run CI/CD script
      run: python run_ci_cd.py
